	kernel u0 (
		.clk_clk                              (<connected-to-clk_clk>),                              //                           clk.clk
		.ir_1506_conduit_end_0_export         (<connected-to-ir_1506_conduit_end_0_export>),         //         ir_1506_conduit_end_0.export
		.lcd_1506_conduit_end_0_export_data   (<connected-to-lcd_1506_conduit_end_0_export_data>),   //        lcd_1506_conduit_end_0.export_data
		.lcd_1506_conduit_end_0_export_rw     (<connected-to-lcd_1506_conduit_end_0_export_rw>),     //                              .export_rw
		.lcd_1506_conduit_end_0_export_en     (<connected-to-lcd_1506_conduit_end_0_export_en>),     //                              .export_en
		.lcd_1506_conduit_end_0_export_rs     (<connected-to-lcd_1506_conduit_end_0_export_rs>),     //                              .export_rs
		.lcd_1506_conduit_end_0_export_blon   (<connected-to-lcd_1506_conduit_end_0_export_blon>),   //                              .export_blon
		.lcd_1506_conduit_end_0_export_on     (<connected-to-lcd_1506_conduit_end_0_export_on>),     //                              .export_on
		.new_sdram_controller_wire_addr       (<connected-to-new_sdram_controller_wire_addr>),       //     new_sdram_controller_wire.addr
		.new_sdram_controller_wire_ba         (<connected-to-new_sdram_controller_wire_ba>),         //                              .ba
		.new_sdram_controller_wire_cas_n      (<connected-to-new_sdram_controller_wire_cas_n>),      //                              .cas_n
		.new_sdram_controller_wire_cke        (<connected-to-new_sdram_controller_wire_cke>),        //                              .cke
		.new_sdram_controller_wire_cs_n       (<connected-to-new_sdram_controller_wire_cs_n>),       //                              .cs_n
		.new_sdram_controller_wire_dq         (<connected-to-new_sdram_controller_wire_dq>),         //                              .dq
		.new_sdram_controller_wire_dqm        (<connected-to-new_sdram_controller_wire_dqm>),        //                              .dqm
		.new_sdram_controller_wire_ras_n      (<connected-to-new_sdram_controller_wire_ras_n>),      //                              .ras_n
		.new_sdram_controller_wire_we_n       (<connected-to-new_sdram_controller_wire_we_n>),       //                              .we_n
		.pio_0_external_connection_export     (<connected-to-pio_0_external_connection_export>),     //     pio_0_external_connection.export
		.pio_1_external_connection_export     (<connected-to-pio_1_external_connection_export>),     //     pio_1_external_connection.export
		.pio_2_external_connection_export     (<connected-to-pio_2_external_connection_export>),     //     pio_2_external_connection.export
		.pio_3_external_connection_export     (<connected-to-pio_3_external_connection_export>),     //     pio_3_external_connection.export
		.pio_4_external_connection_export     (<connected-to-pio_4_external_connection_export>),     //     pio_4_external_connection.export
		.pio_5_external_connection_export     (<connected-to-pio_5_external_connection_export>),     //     pio_5_external_connection.export
		.pio_6_external_connection_export     (<connected-to-pio_6_external_connection_export>),     //     pio_6_external_connection.export
		.pio_7_external_connection_export     (<connected-to-pio_7_external_connection_export>),     //     pio_7_external_connection.export
		.reset_reset_n                        (<connected-to-reset_reset_n>),                        //                         reset.reset_n
		.user_gio_pwm_0_conduit_end_0_export  (<connected-to-user_gio_pwm_0_conduit_end_0_export>),  //  user_gio_pwm_0_conduit_end_0.export
		.user_gio_pwm_10_conduit_end_0_export (<connected-to-user_gio_pwm_10_conduit_end_0_export>), // user_gio_pwm_10_conduit_end_0.export
		.user_gio_pwm_11_conduit_end_0_export (<connected-to-user_gio_pwm_11_conduit_end_0_export>), // user_gio_pwm_11_conduit_end_0.export
		.user_gio_pwm_12_conduit_end_0_export (<connected-to-user_gio_pwm_12_conduit_end_0_export>), // user_gio_pwm_12_conduit_end_0.export
		.user_gio_pwm_13_conduit_end_0_export (<connected-to-user_gio_pwm_13_conduit_end_0_export>), // user_gio_pwm_13_conduit_end_0.export
		.user_gio_pwm_14_conduit_end_0_export (<connected-to-user_gio_pwm_14_conduit_end_0_export>), // user_gio_pwm_14_conduit_end_0.export
		.user_gio_pwm_15_conduit_end_0_export (<connected-to-user_gio_pwm_15_conduit_end_0_export>), // user_gio_pwm_15_conduit_end_0.export
		.user_gio_pwm_16_conduit_end_0_export (<connected-to-user_gio_pwm_16_conduit_end_0_export>), // user_gio_pwm_16_conduit_end_0.export
		.user_gio_pwm_17_conduit_end_0_export (<connected-to-user_gio_pwm_17_conduit_end_0_export>), // user_gio_pwm_17_conduit_end_0.export
		.user_gio_pwm_1_conduit_end_0_export  (<connected-to-user_gio_pwm_1_conduit_end_0_export>),  //  user_gio_pwm_1_conduit_end_0.export
		.user_gio_pwm_2_conduit_end_0_export  (<connected-to-user_gio_pwm_2_conduit_end_0_export>),  //  user_gio_pwm_2_conduit_end_0.export
		.user_gio_pwm_3_conduit_end_0_export  (<connected-to-user_gio_pwm_3_conduit_end_0_export>),  //  user_gio_pwm_3_conduit_end_0.export
		.user_gio_pwm_4_conduit_end_0_export  (<connected-to-user_gio_pwm_4_conduit_end_0_export>),  //  user_gio_pwm_4_conduit_end_0.export
		.user_gio_pwm_5_conduit_end_0_export  (<connected-to-user_gio_pwm_5_conduit_end_0_export>),  //  user_gio_pwm_5_conduit_end_0.export
		.user_gio_pwm_6_conduit_end_0_export  (<connected-to-user_gio_pwm_6_conduit_end_0_export>),  //  user_gio_pwm_6_conduit_end_0.export
		.user_gio_pwm_7_conduit_end_0_export  (<connected-to-user_gio_pwm_7_conduit_end_0_export>),  //  user_gio_pwm_7_conduit_end_0.export
		.user_gio_pwm_8_conduit_end_0_export  (<connected-to-user_gio_pwm_8_conduit_end_0_export>),  //  user_gio_pwm_8_conduit_end_0.export
		.user_gio_pwm_9_conduit_end_0_export  (<connected-to-user_gio_pwm_9_conduit_end_0_export>)   //  user_gio_pwm_9_conduit_end_0.export
	);

