/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  3.3 SP1
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2015 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "ADC_SAR_L.h"
#include "LCD.h"
#include "ADC_SAR_R.h"
#include "UART_1.h"
#include "UART_2.h"
#include "UART_3.h"
#include "UART_4.h"
#include "UART_5.h"
#include "RX_aliases.h"
#include "RX.h"
#include "ADC_SAR_L_IRQ.h"
#include "ADC_SAR_L_theACLK.h"
#include "ADC_SAR_L_Bypass_aliases.h"
#include "ADC_SAR_L_Bypass.h"
#include "LCD_LCDPort_aliases.h"
#include "LCD_LCDPort.h"
#include "ADC_SAR_R_IRQ.h"
#include "ADC_SAR_R_theACLK.h"
#include "UART_1_IntClock.h"
#include "UART_2_IntClock.h"
#include "UART_3_IntClock.h"
#include "UART_4_IntClock.h"
#include "UART_5_IntClock.h"
#include "core_cm3_psoc5.h"
#include "core_cm3.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "core_cmFunc.h"
#include "core_cmInstr.h"

/*[]*/

